services:
  product-service:
    build: 
      context: ./services/Product_Service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./services/Product_Service:/app

  user-service:
    ports:
      - "3002:3002"
